# Generated by Django 5.0.6 on 2024-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSeating', '0002_invigilatordetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invigilatordetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='invigilatordetails',
            name='unique_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
