# Generated by Django 5.0.6 on 2024-07-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSeating', '0007_studentcompletedetails_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcompletedetails',
            name='branch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcompletedetails',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
