# Generated by Django 5.0.6 on 2024-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('room_floor', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
            ],
        ),
    ]
