# Generated by Django 5.0.6 on 2024-07-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSeating', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='RoomDetails',
        ),
    ]
